version: "3.9"
services:
  ReactJS-dev:
    image: anicmarko9/frontend:1.1
    container_name: ReactJS-dev
  NodeJS-dev:
    image: anicmarko9/backend:2.8
    container_name: NodeJS-dev
    depends_on:
      - PostgreSQL
  PostgreSQL:
    container_name: PostgreSQL
    image: postgres:15-alpine
  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:6