# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment-prod
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-prod
  template:
    metadata:
      labels:
        app: react-prod
    spec:
      containers:
      - name: react-prod
        image: anicmarko9/front-prod:1.0
        env:
          - name: TZ
            value: Europe/Amsterdam
          - name: REACT_APP_SERVER_URL
            value: http://localhost:5010/
          - name: NODE_ENV
            value: production
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: "500Mi"
            cpu: "0.1"
        ports:
        - containerPort: 80
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: react-service-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: react-prod
  ports:
    - name: http
      port: 3010
      targetPort: 80
      nodePort: 30015
      protocol: TCP
