# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment-prod
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-prod
  template:
    metadata:
      labels:
        app: nodejs-prod
    spec:
      containers:
        - name: nodejs-prod
          image: anicmarko9/back-prod:1.4
          envFrom:
            - secretRef:
                name: nodejs-secret
          env:
            - name: PGHOST
              value: ElephantSQL
            - name: TZ
              value: Europe/Amsterdam
            - name: NODE_ENV
              value: production
            - name: FRONT_URL
              value: http://localhost:3010
            - name: PORT
              value: "5010"
          ports:
            - containerPort: 5010
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              memory: "500Mi"
              cpu: "0.1"
# In this example, the limits section sets a maximum of 1 GiB of memory and 0.5 CPU units that can be used by the pod, while the requests section sets a minimum of 500 MiB of memory and 0.1 CPU units that the pod requires.
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: nodejs-prod
  ports:
    - name: http
      port: 5010
      targetPort: 5010
      nodePort: 30010
