version: "3.9"
services:
  weather-back:
    container_name: NodeJS-production
    image: anicmarko9/back-prod:1.2
    restart: always
    build: .
    networks:
      - back-prod
      - front-prod
    ports:
      - 5000:80
    env_file: .env
    environment:
      - PGHOST=ElephantSQL
      - TZ=Europe/Amsterdam
      - NODE_ENV=production
networks:
  back-prod:
    name: back-prod
  front-prod:
    name: front-prod
    external: true