version: "3.9"
name: development
services:
  ReactJS-dev:
    container_name: ReactJS-dev
    image: anicmarko9/frontend:1.1
    restart: always
    build:
      context: ./../../frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file: ./../../frontend/.env
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - front
      - back
  NodeJS-dev:
    container_name: NodeJS-dev
    image: anicmarko9/backend:2.8
    restart: always
    build:
      context: ./../../backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    env_file: ./../../backend/.env
    environment:
      - PGHOST=PostgreSQL
      - TZ=Europe/Amsterdam
      - NODE_ENV=development
    depends_on:
      - PostgreSQL
    networks:
      - back
      - front
  PostgreSQL:
    container_name: PostgreSQL
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    env_file: ./../../backend/.postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db
      - back
  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:6
    restart: always
    ports:
      - 80:80
    env_file: ./../../backend/.pgadmin.env
    depends_on:
      - PostgreSQL
    networks:
      - db
      - back
volumes:
  postgres-data:
    name: postgres-data
    driver: local
networks:
  db:
    name: db
    internal: true
  back:
    name: back
  front:
    name: front